const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const money=n=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(n)||0);
const parseMoney=v=>{let s=String(v||'').replace(/R\$/gi,'').replace(/\s/g,'');if(s.includes(','))s=s.replace(/\./g,'').replace(',','.');const n=Number(s);return Number.isFinite(n)?n:0};
const state=JSON.parse(localStorage.getItem('cuidaDinheiro')||'{"movements":[],"bills":[],"color":"#16a34a","theme":"light"}');
function save(){localStorage.setItem('cuidaDinheiro',JSON.stringify(state));render()}
function totals(){const income=state.movements.filter(x=>x.type==='income').reduce((s,x)=>s+x.amount,0);const expense=state.movements.filter(x=>x.type==='expense').reduce((s,x)=>s+x.amount,0);const pending=state.bills.filter(x=>!x.paid).reduce((s,x)=>s+x.amount,0);const balance=income-expense;return{income,expense,pending,balance,free:balance-pending}}
function movementRow(m){const el=document.createElement('div');el.className='row';el.innerHTML=`<div><div class="name"></div><div class="meta"></div></div><div class="amount ${m.type==='income'?'in':'out'}"></div>`;el.querySelector('.name').textContent=m.description||m.category;el.querySelector('.meta').textContent=`${m.category} • ${new Date(m.createdAt).toLocaleDateString('pt-BR')}`;el.querySelector('.amount').textContent=(m.type==='income'?'+ ':'− ')+money(m.amount);return el}
function renderList(target,items,empty){const box=$(target);box.innerHTML='';if(!items.length){box.innerHTML=`<div class="empty">${empty}</div>`;return}items.forEach(x=>box.appendChild(movementRow(x)))}
function renderBills(){const box=$('#billsList');box.innerHTML='';if(!state.bills.length){box.innerHTML='<div class="empty">Nenhuma conta cadastrada.</div>';return}state.bills.slice().sort((a,b)=>(a.due||'9999').localeCompare(b.due||'9999')).forEach(b=>{const r=document.createElement('div');r.className='row';const left=document.createElement('div');left.innerHTML='<div class="name"></div><div class="meta"></div>';left.querySelector('.name').textContent=b.name;left.querySelector('.meta').textContent=(b.due?'Vence '+new Date(b.due+'T12:00:00').toLocaleDateString('pt-BR'):'Sem vencimento')+(b.paid?' • paga':' • pendente');const right=document.createElement('div');right.style.textAlign='right';const val=document.createElement('div');val.className='amount';val.textContent=money(b.amount);const btn=document.createElement('button');btn.className='btn ghost';btn.style.minHeight='36px';btn.style.marginTop='6px';btn.textContent=b.paid?'Reabrir':'Paguei';btn.onclick=()=>{b.paid=!b.paid;save()};right.append(val,btn);r.append(left,right);box.append(r)})}
function applyTheme(){document.documentElement.style.setProperty('--primary',state.color||'#16a34a');document.documentElement.style.setProperty('--primary-soft',hexToRgba(state.color||'#16a34a',.13));if(state.theme==='dark'){document.documentElement.style.setProperty('--bg','#0b1220');document.documentElement.style.setProperty('--card','#111827');document.documentElement.style.setProperty('--text','#f8fafc');document.documentElement.style.setProperty('--muted','#94a3b8');document.documentElement.style.setProperty('--border','#243044')}else{document.documentElement.style.setProperty('--bg','#f8fafc');document.documentElement.style.setProperty('--card','#ffffff');document.documentElement.style.setProperty('--text','#0f172a');document.documentElement.style.setProperty('--muted','#64748b');document.documentElement.style.setProperty('--border','#e2e8f0')}}
function hexToRgba(hex,a){const n=parseInt(hex.slice(1),16);return `rgba(${n>>16},${(n>>8)&255},${n&255},${a})`}
function render(){applyTheme();const t=totals();$('#freeMoney').textContent=money(t.free);$('#balance').textContent=money(t.balance);$('#income').textContent=money(t.income);$('#expense').textContent=money(t.expense);$('#pending').textContent=money(t.pending);$('#resultMoney').textContent=money(t.balance);$('#analysisText').textContent=t.balance<0?'Você está gastando mais do que recebe.':t.pending>t.balance?'Seu saldo não cobre todas as contas pendentes.':t.free>0?`Você tem ${money(t.free)} livres depois das contas.`:'Registre seus ganhos e gastos para acompanhar sua situação.';const ordered=state.movements.slice().sort((a,b)=>b.createdAt-a.createdAt);renderList('#recentList',ordered.slice(0,5),'Nenhuma movimentação ainda.');renderList('#allList',ordered,'Nenhuma movimentação ainda.');renderBills();$('#colorPicker').value=state.color||'#16a34a';$('#themeSelect').value=state.theme||'light'}
function openMovement(type){$('#movementType').value=type;$('#movementTitle').textContent=type==='income'?'Nova entrada':'Nova saída';$('#movementForm').reset();$('#movementType').value=type;$('#movementDialog').showModal();setTimeout(()=>$('#movementAmount').focus(),50)}
$('#addIncome').onclick=()=>openMovement('income');$('#addExpense').onclick=()=>openMovement('expense');
$('#movementForm').addEventListener('submit',e=>{e.preventDefault();const amount=parseMoney($('#movementAmount').value);if(amount<=0)return alert('Informe um valor maior que zero.');state.movements.push({id:crypto.randomUUID?.()||String(Date.now()),type:$('#movementType').value,amount,category:$('#movementCategory').value,description:$('#movementDescription').value.trim(),createdAt:Date.now()});$('#movementDialog').close();save()});
function openBill(){$('#billForm').reset();$('#billDialog').showModal()}$('#addBill').onclick=openBill;$('#addBill2').onclick=openBill;
$('#billForm').addEventListener('submit',e=>{e.preventDefault();const amount=parseMoney($('#billAmount').value);if(amount<=0)return alert('Informe um valor maior que zero.');state.bills.push({id:crypto.randomUUID?.()||String(Date.now()),name:$('#billName').value.trim(),amount,due:$('#billDue').value,paid:false});$('#billDialog').close();save()});
$('#canSpend').onclick=()=>{$('#spendForm').reset();$('#spendResult').innerHTML='';$('#spendDialog').showModal()};
$('#spendForm').addEventListener('submit',e=>{e.preventDefault();const value=parseMoney($('#spendAmount').value);if(value<=0)return;const t=totals();const after=t.free-value;const ok=after>=0;$('#spendResult').className='notice'+(ok?'':' bad');$('#spendResult').textContent=ok?`Pode gastar. Depois ainda restariam ${money(after)} livres.`:`Não recomendado. Faltariam ${money(Math.abs(after))} para manter suas contas protegidas.`});
$('#settingsBtn').onclick=()=>$('#settingsDialog').showModal();$('#colorPicker').addEventListener('input',e=>{state.color=e.target.value;save()});$('#themeSelect').addEventListener('change',e=>{state.theme=e.target.value;save()});
$$('[data-close]').forEach(b=>b.onclick=()=>$('#'+b.dataset.close).close());
$$('.nav button').forEach(b=>b.onclick=()=>{$$('.nav button').forEach(x=>x.classList.remove('active'));b.classList.add('active');['homeView','transactionsView','billsView','analysisView'].forEach(id=>$('#'+id).classList.toggle('hidden',id!==b.dataset.view))});
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});render();